name: JPacman CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: xvfb-run ./gradlew build

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

    - name: Check badge creation
      run: ls -l .github/badges
      
    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Add this line
        message: Updated JaCoCo badges
        add: .github/badges/*.svg
        push: true
    - name: Show test results
      run: cat build/reports/jacoco/test/jacocoTestReport.csv
